### ISSUE TITLE
Package isn't configured for NgModule import

### ISSUE THREAD

**Issue by aflegel** [LukasMarx/json-ignore#1]
It seems that the npm package isn't set up for the NgModule for import.

Visual Studio provides this error
'~~/node_modules/json-ignore/index.ts' is not under 'rootDir' 
'~~/wwwroot'. 'rootDir' is expected to contain all source files.

I suspect it has to do with exported functions instead of an exported class.

**Comment by LukasMarx** [comment]
Sry for answering that late. 
I'm not quite sure what you mean by that...

This is a normal TypeScript module and has nothing to do with angular. Therefore you can't import it into an angular module. These are two different types of modules.

I've tried using this module with angular (v5), and it works just fine by importing it into your code:

```
import { Component } from '@angular/core';
import { jsonIgnore, jsonIgnoreReplacer } from 'json-ignore';

class test {
  @jsonIgnore() public test = '123';

  public test2 = '456';
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor() {
    console.log(JSON.stringify(new test(), jsonIgnoreReplacer));
  }
}
```
