### ISSUE TITLE
No Typings for Typescript avaliable

### ISSUE THREAD

**Issue by DMW007** [LukasMarx/json-ignore#2]
It seems that no Typings exist. Neither in the `json-ignore` package itself, nor in the corresponding `@types/json-ignore`. Please provide typings, so that we can use the packet with strongly typings and intellisense in TypeScript. 

Tested Version: json-ignore@0.2.0

**Comment by LukasMarx** [comment]
Fixed in 0.4.0 42b620d1bbec26ad5ff63c4334ffa929c1860fa6
