### ISSUE TITLE
incompatibility with Ngx-Translate/core injection

### ISSUE THREAD

**Issue by Titoch** [LukasMarx/json-ignore#3]
Hello @LukasMarx 
I was using @jsonIgnore in Ionic 2 and ngx-translate 8.0.0. It was ok.

But since I upgraded to Ionic 3.9.2 and Angular 5.2.9, I had to upgrade to ngx-translate 9.x

When I use @json-ignore in any class or component providing ngx-translate the TranslateService can nom more be injected. 
I automatically get the following error:
```
Error: Uncaught (in promise): Error: Can't resolve all parameters for TranslateService: (?, ?, ?, ?, ?, [object Object], [object Object]).
syntaxError@http://localhost:8100/build/vendor.js:83095:34

```

I think there is an incompatibility between ngx-translate/core@9.x and json-ignore dependencies.
So I can no more use json-ignore

My current node-modules are :
     "json-ignore": "^0.4.0",

    "@angular/common": "5.2.9",
    "@ionic-native/core": "4.7.0",
    "@ngx-translate/core": "9.1.1",
    "@ngx-translate/http-loader": "2.0.1",

dev:

    "typescript": "2.6.2",

Installed module reflect-metadata ; is 0.1.10
Not installed : mocha / @types/mocha / benchmark 

Please could you check this point?
Thank you!

**Comment by LukasMarx** [comment]
Hi, 
I set up a new angular project with ngx-translate. It was working fine. I did not try with ionic native though.

However, I managed to reproduce you issue by removing this polyfill from src/polyfill.ts:

`import 'core-js/es7/reflect';` --> works fine

`//import 'core-js/es7/reflect';` -->

Can't resolve all parameters for TranslateService: (?, ?, ?, ?, ?, [object Object], [object Object]).

Please make sure you have this line in your polyfill.ts. 

At this point I am not sure how ionic native works, and if this file even exists there....

If that does not resolve your issue, feel free to tell me.

I hope this helps!

**Comment by Titoch** [comment]
Hi,
There is no src/polyfill.ts in ionic project base. 
I added one but only for jasmine tests.
In build directory there is a polyfill.js... But I can not find anything inside.

I think ionic-angular@3.9.2 module is configured with es2015 (es6) only.

If es7 is mandatory to support json-ignore then I think it can not be actually used in Ionic project.
Is it correct?

**Comment by Titoch** [comment]
Hello,
I've just find a way to avoid error on Ionic.
I added in the main.ts the following line :
import 'reflect-metadata'; 
and @json-ignore décoration if functional.

I don't know side's effects of this modification. I've to look deeper to know them.

**Comment by Titoch** [comment]
I did it in normal way using 
npm install reflect-metadata 
in my package.json.
Now it's ok.
You can close this issue.
Thanks.

**Comment by LukasMarx** [comment]
Glad you've figured it out! Thanks for sharing this.
